-- Seed data for testing semantic search
-- Run this with: sqlite3 ~/Library/Application\ Support/reflective-web/reflective/database.db < scripts/seed-data.sql

INSERT INTO entries (content, created_at, updated_at, word_count) VALUES
('<p>The project deadline is looming and I can feel the pressure mounting. My team has been working late nights trying to get everything ready for the presentation. I''m worried we might not finish in time, but trying to stay focused and tackle one task at a time.</p>', 1728672000000, 1728672000000, 52),
('<p>Had a really productive therapy session today. We talked about my tendency to overthink things and how it creates unnecessary stress. She suggested I try mindfulness meditation when I start feeling overwhelmed. Going to give it a shot this week.</p>', 1728931200000, 1728931200000, 48),
('<p>Finally got back into running this morning! Did a slow 3 miles around the park. My legs are sore but it feels great to be active again. Want to build up to 5 miles by the end of the month. Fresh air and movement really help clear my head.</p>', 1729104000000, 1729104000000, 54),
('<p>Mom called today and we had a long chat about everything going on. It''s nice to have someone who just listens without judgment. She reminded me that it''s okay to not have everything figured out. Family support means everything.</p>', 1729276800000, 1729276800000, 45),
('<p>Started reading "Atomic Habits" and I''m already finding it so insightful. The idea that small changes compound over time really resonates with me. I want to build better routines around sleep and exercise. One percent better every day sounds achievable.</p>', 1729449600000, 1729449600000, 48),
('<p>The anxiety has been creeping back lately. Little things that shouldn''t bother me feel overwhelming. I notice my chest getting tight and my thoughts racing. Need to remember the breathing exercises and maybe schedule another session with my therapist.</p>', 1729622400000, 1729622400000, 45),
('<p>We shipped the product today! All those late nights and stressful meetings paid off. The client loved the presentation and we got approval to move forward. Team went out to celebrate - feels amazing to see hard work recognized. So relieved the pressure is off.</p>', 1729795200000, 1729795200000, 50),
('<p>Hit a new personal record at the gym today - benched 185 pounds! My trainer says my form has improved a lot. Consistent workouts are definitely paying off. Feeling strong and energized. This is exactly why I keep showing up.</p>', 1729968000000, 1729968000000, 45),
('<p>Coffee with Sarah was exactly what I needed. We laughed about old memories and she gave me great advice about the work situation. True friends who really know you are rare. Grateful to have her in my corner. Left feeling lighter and more optimistic.</p>', 1730140800000, 1730140800000, 50),
('<p>Tried a new recipe tonight - homemade pasta from scratch. It was messy and took forever, but the end result was delicious. Cooking is becoming my creative outlet. There''s something therapeutic about following a recipe and creating something with your hands.</p>', 1730313600000, 1730313600000, 47),
('<p>Woke up feeling uncertain about everything today. Career path, relationships, where I''m heading. Sometimes the weight of decisions feels paralyzing. Taking it one day at a time is all I can do right now. Tomorrow will bring new perspective.</p>', 1730486400000, 1730486400000, 45),
('<p>Morning meditation practice is starting to stick. Twenty minutes of just sitting and breathing. My mind still wanders constantly but I''m learning to notice thoughts without attaching to them. Finding moments of calm in the chaos feels revolutionary.</p>', 1730659200000, 1730659200000, 45),
('<p>Team conflict today was rough. Different opinions about project direction led to heated discussion. I hate confrontation but spoke up anyway. Sometimes you have to advocate for what you believe is right even when it''s uncomfortable. Hoping we can find middle ground tomorrow.</p>', 1730745600000, 1730745600000, 50),
('<p>Six mile run this morning! Couldn''t have imagined doing that a month ago. The endorphins afterward are incredible. Running gives me time to process thoughts and work through problems. My mental health has improved so much since I started exercising regularly.</p>', 1730832000000, 1730832000000, 48),
('<p>Date night was wonderful. We tried that new Italian place downtown and just talked for hours. It''s easy to take relationships for granted when life gets busy. Making time for connection is so important. Fell asleep feeling loved and appreciated.</p>', 1730918400000, 1730918400000, 45),
('<p>Grateful for: my health, supportive friends, meaningful work, morning coffee, good books, and the ability to grow and change. Even on hard days, there''s always something to appreciate. Focusing on gratitude shifts my entire mindset.</p>', 1731004800000, 1731004800000, 42),
('<p>Setting goals for next month: run a 10K, finish two books, cook three new recipes, and maintain daily meditation. Also want to be more present with loved ones and less absorbed in screens. Progress over perfection.</p>', 1730227200000, 1730227200000, 44),
('<p>Tough day at the office. Deadline pressure is back and tensions are high. My manager piled on extra work right when I thought things were settling down. Feeling stretched thin and exhausted. Need to set better boundaries but don''t know how without seeming difficult.</p>', 1730572800000, 1730572800000, 50);
